[build]
  command = "npm run build" # or "yarn build" if you are using yarn
  publish = "dist" # The directory where the build output is placed
  functions = "netlify/functions" # Directory for Netlify Functions if you have any

[dev]
  command = "npm run dev" # or "yarn dev"
  port = 8888
  targetPort = 5173

[[redirects]]
  from = "/hello"
  to = "/.netlify/functions/hello"
  status = 200